set windows-shell := ["pwsh", "-NoLogo", "-NoProfileLoadTime", "-Command"]

build:
  npx rspack --mode production -c ./rspack.config.cjs

dev:
  npx rspack dev --mode production -c ./rspack.config.cjs

test: 
  node --import tsx --test "./src/platform/intents/intents-service.test.ts"